steps:
  - id: "Rodando testes"
    name: 'mirror.gcr.io/library/golang'
    env: ['GO111MODULE=on']
    args: ['go', 'test', '-v']

  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
    args: ['-f', 'docker-compose.yaml', 'up', '-d', '--build']

images: ['gcr.io/$PROJECT_ID/gout:latest']